# For more information, look at 
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: "2"

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub
